<?php

namespace Database\Seeders;

use App\Models\Dealer;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class DealerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $dealers = [
            [

                "kode" => "00000",
                "ahass" => "Main Dealer",
                "kota_kab" => "BALIKPAPAN",
                "kecamatan" => "BALIKPAPAN SELATAN",
                "status" => "MAINDEALER",
                "se_area" => "ADMIN",
                "group" => "A",
                "kode_customer" => "00000",
                "created_at" => null,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [

                "kode" => "00576",
                "ahass" => "PT. HARAPAN UTAMA MAKMUR - KARANGJATI",
                "kota_kab" => "BALIKPAPAN",
                "kecamatan" => "BALIKPAPAN TENGAH",
                "status" => "BALIKPAPAN TENGAH",
                "se_area" => "H123",
                "group" => "Alfaj",
                "kode_customer" => "5200009965",
                "created_at" => "2025/1/14 09:41:35",
                "updated_at" => "2025/1/14 09:41:35",
                "deleted_at" => null,
            ],
            [

                "kode" => "01858",
                "ahass" => "PT. HARAPAN UTAMA MAKMUR - DAMAI",
                "kota_kab" => "BALIKPAPAN",
                "kecamatan" => "BALIKPAPAN KOTA",
                "status" => "BALIKPAPAN KOTA",
                "se_area" => "H123",
                "group" => "Alfaj",
                "kode_customer" => "5200009966",
                "created_at" => "2025/1/14 09:41:35",
                "updated_at" => "2025/1/14 09:41:35",
                "deleted_at" => null,
            ],
            [

                "kode" => "01963",
                "ahass" => "CV. DAYA MAKMUR MANDIRI",
                "kota_kab" => "BALIKPAPAN",
                "kecamatan" => "BALIKPAPAN BARAT",
                "status" => "BALIKPAPAN BARAT",
                "se_area" => "H123",
                "group" => "Alfaj",
                "kode_customer" => "5200009964",
                "created_at" => "2025/1/14 09:41:35",
                "updated_at" => "2025/1/14 09:41:35",
                "deleted_at" => null,
            ],
            [

                "kode" => "02260",
                "ahass" => "ROMAN MOTOR",
                "kota_kab" => "BALIKPAPAN",
                "kecamatan" => "BALIKPAPAN TIMUR",
                "status" => "BALIKPAPAN TIMUR",
                "se_area" => "H23",
                "group" => "Daniel",
                "kode_customer" => "5200010034",
                "created_at" => "2025/1/14 09:41:35",
                "updated_at" => "2025/1/14 09:41:35",
                "deleted_at" => null,
            ],
            [

                "kode" => "02703",
                "ahass" => "PT. HARAPAN UTAMA MAKMUR - CITRA BARU SEPINGGAN",
                "kota_kab" => "BALIKPAPAN",
                "kecamatan" => "BALIKPAPAN SELATAN",
                "status" => "BALIKPAPAN SELATAN",
                "se_area" => "H23",
                "group" => "Alfaj",
                "kode_customer" => "5200021703",
                "created_at" => "2025/1/14 09:41:35",
                "updated_at" => "2025/1/14 09:41:35",
                "deleted_at" => null,
            ],
            [

                "kode" => "06828",
                "ahass" => "WIRAWAN MOTOR",
                "kota_kab" => "BALIKPAPAN",
                "kecamatan" => "BALIKPAPAN UTARA",
                "status" => "BALIKPAPAN UTARA",
                "se_area" => "H23",
                "group" => "Daniel",
                "kode_customer" => "5200010450",
                "created_at" => "2025/1/14 09:41:35",
                "updated_at" => "2025/1/14 09:41:35",
                "deleted_at" => null,
            ],
            [

                "kode" => "10282",
                "ahass" => "PT. DAYA ANUGRAH MANDIRI - BALIKPAPAN",
                "kota_kab" => "BALIKPAPAN",
                "kecamatan" => "BALIKPAPAN TENGAH",
                "status" => "BALIKPAPAN TENGAH",
                "se_area" => "H123",
                "group" => "Alfaj",
                "kode_customer" => "5200009972",
                "created_at" => "2025/1/14 09:41:35",
                "updated_at" => "2025/1/14 09:41:35",
                "deleted_at" => null,
            ],
            [

                "kode" => "12599",
                "ahass" => "ASTRA MOTOR - SUDIRMAN",
                "kota_kab" => "BALIKPAPAN",
                "kecamatan" => "BALIKPAPAN KOTA",
                "status" => "BALIKPAPAN KOTA",
                "se_area" => "H123",
                "group" => "Daniel",
                "kode_customer" => "H703",
                "created_at" => "2025/1/14 09:41:35",
                "updated_at" => "2025/1/14 09:41:35",
                "deleted_at" => null,
            ],
            [

                "kode" => "11003",
                "ahass" => "ASTRA MOTOR - MT. HARYONO",
                "kota_kab" => "BALIKPAPAN",
                "kecamatan" => "BALIKPAPAN SELATAN",
                "status" => "BALIKPAPAN SELATAN",
                "se_area" => "H123",
                "group" => "Daniel",
                "kode_customer" => "H701",
                "created_at" => "2025/1/14 09:41:35",
                "updated_at" => "2025/1/14 09:41:35",
                "deleted_at" => null,
            ],
            [

                "kode" => "12086",
                "ahass" => "PT. NUSANTARA SURYA SAKTI - BALIKPAPAN",
                "kota_kab" => "BALIKPAPAN",
                "kecamatan" => "BALIKPAPAN UTARA",
                "status" => "BALIKPAPAN UTARA",
                "se_area" => "H123",
                "group" => "Daniel",
                "kode_customer" => "5200009974",
                "created_at" => "2025/1/14 09:41:35",
                "updated_at" => "2025/1/14 09:41:35",
                "deleted_at" => null,
            ],
            [

                "kode" => "13136",
                "ahass" => "RIZKI MOTOR",
                "kota_kab" => "BALIKPAPAN",
                "kecamatan" => "BALIKPAPAN KOTA",
                "status" => "BALIKPAPAN KOTA",
                "se_area" => "H23",
                "group" => "Alfaj",
                "kode_customer" => "5200017940",
                "created_at" => "2025/1/14 09:41:35",
                "updated_at" => "2025/1/14 09:41:35",
                "deleted_at" => null,
            ],
            [

                "kode" => "10254",
                "ahass" => "PT. TUNAS DWIPA MATRA - BALIKPAPAN",
                "kota_kab" => "BALIKPAPAN",
                "kecamatan" => "BALIKPAPAN TIMUR",
                "status" => "BALIKPAPAN TIMUR",
                "se_area" => "H123",
                "group" => "Alfaj",
                "kode_customer" => "2100005036",
                "created_at" => "2025/1/14 09:41:35",
                "updated_at" => "2025/1/14 09:41:35",
                "deleted_at" => null,
            ],
            [

                "kode" => "12958",
                "ahass" => "ASTRA MOTOR - SEPINGGAN",
                "kota_kab" => "BALIKPAPAN",
                "kecamatan" => "BALIKPAPAN SELATAN",
                "status" => "BALIKPAPAN SELATAN",
                "se_area" => "H123",
                "group" => "Daniel",
                "kode_customer" => "H706",
                "created_at" => "2025/1/14 09:41:35",
                "updated_at" => "2025/1/14 09:41:35",
                "deleted_at" => null,
            ],
            [

                "kode" => "12600",
                "ahass" => "ASTRA MOTOR - KILO",
                "kota_kab" => "BALIKPAPAN",
                "kecamatan" => "BALIKPAPAN UTARA",
                "status" => "BALIKPAPAN UTARA",
                "se_area" => "H123",
                "group" => "Daniel",
                "kode_customer" => "H705",
                "created_at" => "2025/1/14 09:41:35",
                "updated_at" => "2025/1/14 09:41:35",
                "deleted_at" => null,
            ],
            [

                "kode" => "18035",
                "ahass" => "DWI MOTOR",
                "kota_kab" => "BALIKPAPAN",
                "kecamatan" => "BALIKPAPAN UTARA",
                "status" => "BALIKPAPAN UTARA",
                "se_area" => "H23",
                "group" => "Alfaj",
                "kode_customer" => "5200022576",
                "created_at" => "2025/1/14 09:41:35",
                "updated_at" => "2025/1/14 09:41:35",
                "deleted_at" => null,
            ],
            [

                "kode" => "18036",
                "ahass" => "RIZKI KILO",
                "kota_kab" => "BALIKPAPAN",
                "kecamatan" => "BALIKPAPAN UTARA",
                "status" => "BALIKPAPAN UTARA",
                "se_area" => "H23",
                "group" => "Alfaj",
                "kode_customer" => "5200022411",
                "created_at" => "2025/1/14 09:41:35",
                "updated_at" => "2025/1/14 09:41:35",
                "deleted_at" => null,
            ],
            [

                "kode" => "06324",
                "ahass" => "PT. HARAPAN UTAMA MAKMUR - GUNUNG SARI",
                "kota_kab" => "BALIKPAPAN",
                "kecamatan" => "BALIKPAPAN TENGAH",
                "status" => "BALIKPAPAN TENGAH",
                "se_area" => "H123",
                "group" => "Alfaj",
                "kode_customer" => "5200022714",
                "created_at" => "2025/1/14 09:41:35",
                "updated_at" => "2025/1/14 09:41:35",
                "deleted_at" => null,
            ],
            [

                "kode" => "18615",
                "ahass" => "ELVIA JAYA",
                "kota_kab" => "BALIKPAPAN",
                "kecamatan" => "BALIKPAPAN UTARA",
                "status" => "BALIKPAPAN UTARA",
                "se_area" => "H23",
                "group" => "Alfaj",
                "kode_customer" => "5200023920",
                "created_at" => "2025/1/14 09:41:35",
                "updated_at" => "2025/1/14 09:41:35",
                "deleted_at" => null,
            ],
            [

                "kode" => "01430",
                "ahass" => "PT. HARAPAN UTAMA MAKMUR - PETUNG",
                "kota_kab" => "PENAJAM PASER UTARA",
                "kecamatan" => "PENAJAM",
                "status" => "PENAJAM",
                "se_area" => "H123",
                "group" => "Alfaj",
                "kode_customer" => "5200009971",
                "created_at" => "2025/1/14 09:41:35",
                "updated_at" => "2025/1/14 09:41:35",
                "deleted_at" => null,
            ],
            [

                "kode" => "15203",
                "ahass" => "ASTRA MOTOR - PENAJAM",
                "kota_kab" => "PENAJAM PASER UTARA",
                "kecamatan" => "PENAJAM",
                "status" => "PENAJAM",
                "se_area" => "H123",
                "group" => "Alfaj",
                "kode_customer" => "H704",
                "created_at" => "2025/1/14 09:41:35",
                "updated_at" => "2025/1/14 09:41:35",
                "deleted_at" => null,
            ],
            [

                "kode" => "02257",
                "ahass" => "WIRA BHAKTI",
                "kota_kab" => "PENAJAM PASER UTARA",
                "kecamatan" => "PENAJAM",
                "status" => "PENAJAM",
                "se_area" => "H23",
                "group" => "Alfaj",
                "kode_customer" => "5200010021",
                "created_at" => "2025/1/14 09:41:35",
                "updated_at" => "2025/1/14 09:41:35",
                "deleted_at" => null,
            ],
            [

                "kode" => "02261",
                "ahass" => "WIBISONO",
                "kota_kab" => "PENAJAM PASER UTARA",
                "kecamatan" => "SEPAKU",
                "status" => "SEPAKU",
                "se_area" => "H23",
                "group" => "Alfaj",
                "kode_customer" => "5200010035",
                "created_at" => "2025/1/14 09:41:35",
                "updated_at" => "2025/1/14 09:41:35",
                "deleted_at" => null,
            ],
            [

                "kode" => "10283",
                "ahass" => "PT. DAYA ANUGRAH MANDIRI - PENAJAM",
                "kota_kab" => "PENAJAM PASER UTARA",
                "kecamatan" => "PENAJAM",
                "status" => "PENAJAM",
                "se_area" => "H123",
                "group" => "Alfaj",
                "kode_customer" => "5200009973",
                "created_at" => "2025/1/14 09:41:35",
                "updated_at" => "2025/1/14 09:41:35",
                "deleted_at" => null,
            ],
            [

                "kode" => "12085",
                "ahass" => "ASTRA MOTOR - TANAH GROGOT",
                "kota_kab" => "PASER",
                "kecamatan" => "TANAH GROGOT",
                "status" => "TANAH GROGOT",
                "se_area" => "H123",
                "group" => "Alfaj",
                "kode_customer" => "H702",
                "created_at" => "2025/1/14 09:41:35",
                "updated_at" => "2025/1/14 09:41:35",
                "deleted_at" => null,
            ],
            [

                "kode" => "10255",
                "ahass" => "PT. TUNAS DWIPA MATRA - TANAH GROGOT",
                "kota_kab" => "PASER",
                "kecamatan" => "TANAH GROGOT",
                "status" => "TANAH GROGOT",
                "se_area" => "H123",
                "group" => "Alfaj",
                "kode_customer" => "2100005037",
                "created_at" => "2025/1/14 09:41:35",
                "updated_at" => "2025/1/14 09:41:35",
                "deleted_at" => null,
            ],
            [

                "kode" => "13627",
                "ahass" => "ASTRA MOTOR - SIMPANG PAIT",
                "kota_kab" => "PASER",
                "kecamatan" => "LONG IKIS",
                "status" => "LONG IKIS",
                "se_area" => "H123",
                "group" => "Alfaj",
                "kode_customer" => "H707",
                "created_at" => "2025/1/14 09:41:35",
                "updated_at" => "2025/1/14 09:41:35",
                "deleted_at" => null,
            ],
            [

                "kode" => "00762",
                "ahass" => "UD. CITRA JAYA MOTOR",
                "kota_kab" => "BERAU",
                "kecamatan" => "TANJUNG REDEB",
                "status" => "TANJUNG REDEB",
                "se_area" => "H23",
                "group" => "Daniel",
                "kode_customer" => "5200020006",
                "created_at" => "2025/1/14 09:41:35",
                "updated_at" => "2025/1/14 09:41:35",
                "deleted_at" => null,
            ],
            [

                "kode" => "02677",
                "ahass" => "CV. SUMBER JAYA ABADI MOTOR",
                "kota_kab" => "BERAU",
                "kecamatan" => "TANJUNG REDEB",
                "status" => "TANJUNG REDEB",
                "se_area" => "H123",
                "group" => "Daniel",
                "kode_customer" => "5200019480",
                "created_at" => "2025/1/14 09:41:35",
                "updated_at" => "2025/1/14 09:41:35",
                "deleted_at" => null,
            ],
            [

                "kode" => "16835",
                "ahass" => "ASTRA MOTOR - BERAU",
                "kota_kab" => "BERAU",
                "kecamatan" => "TANJUNG REDEB",
                "status" => "TANJUNG REDEB",
                "se_area" => "H123",
                "group" => "Daniel",
                "kode_customer" => "H713",
                "created_at" => "2025/1/14 09:41:35",
                "updated_at" => "2025/1/14 09:41:35",
                "deleted_at" => null,
            ],
            [

                "kode" => "16453",
                "ahass" => "ASTRA MOTOR - TANJUNG SELOR",
                "kota_kab" => "BULUNGAN",
                "kecamatan" => "TANJUNG SELOR",
                "status" => "TANJUNG SELOR",
                "se_area" => "H123",
                "group" => "Daniel",
                "kode_customer" => "H715",
                "created_at" => "2025/1/14 09:41:35",
                "updated_at" => "2025/1/14 09:41:35",
                "deleted_at" => null,
            ],
            [

                "kode" => "01609",
                "ahass" => "UD. INDRA MOTOR",
                "kota_kab" => "TARAKAN",
                "kecamatan" => "TARAKAN TENGAH",
                "status" => "TARAKAN TENGAH",
                "se_area" => "H23",
                "group" => "Daniel",
                "kode_customer" => "5200019573",
                "created_at" => "2025/1/14 09:41:35",
                "updated_at" => "2025/1/14 09:41:35",
                "deleted_at" => null,
            ],
            [

                "kode" => "13529",
                "ahass" => "MOTOR MEGA TANO",
                "kota_kab" => "TARAKAN",
                "kecamatan" => "TARAKAN BARAT",
                "status" => "TARAKAN BARAT",
                "se_area" => "H123",
                "group" => "Daniel",
                "kode_customer" => "5200019477",
                "created_at" => "2025/1/14 09:41:35",
                "updated_at" => "2025/1/14 09:41:35",
                "deleted_at" => null,
            ],
            [

                "kode" => "16452",
                "ahass" => "ASTRA MOTOR - TARAKAN",
                "kota_kab" => "TARAKAN",
                "kecamatan" => "TARAKAN BARAT",
                "status" => "TARAKAN BARAT",
                "se_area" => "H123",
                "group" => "Daniel",
                "kode_customer" => "H712",
                "created_at" => "2025/1/14 09:41:35",
                "updated_at" => "2025/1/14 09:41:35",
                "deleted_at" => null,
            ],
            [

                "kode" => "13696",
                "ahass" => "DELAPAN JAYA",
                "kota_kab" => "NUNUKAN",
                "kecamatan" => "NUNUKAN",
                "status" => "NUNUKAN",
                "se_area" => "H123",
                "group" => "Daniel",
                "kode_customer" => "5200019476",
                "created_at" => "2025/1/14 09:41:35",
                "updated_at" => "2025/1/14 09:41:35",
                "deleted_at" => null,
            ],
            [

                "kode" => "16762",
                "ahass" => "PT. NUSANTARA SURYA SAKTI - NUNUKAN",
                "kota_kab" => "NUNUKAN",
                "kecamatan" => "NUNUKAN",
                "status" => "NUNUKAN",
                "se_area" => "H123",
                "group" => "Daniel",
                "kode_customer" => "5200020001",
                "created_at" => "2025/1/14 09:41:35",
                "updated_at" => "2025/1/14 09:41:35",
                "deleted_at" => null,
            ],
        ];


        Dealer::insert($dealers);
    }
}
