<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('menus')->insert([
            // Top-level menus
            [
                'id' => 1,
                'name' => 'Dashboard',
                'route' => 'dashboard.index',
                'parent_id' => null,
                'icon' => 'fas fa-chart-pie',
                'color' => null,
                'order' => 1,
                'is_active' => true,
                'permission_name' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'name' => 'Products',
                'route' => null,
                'parent_id' => null,
                'icon' => 'fas fa-box',
                'color' => null,
                'order' => 2,
                'is_active' => true,
                'permission_name' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'name' => 'Management User',
                'route' => 'users.index',
                'parent_id' => null,
                'icon' => 'fas fa-users',
                'color' => null,
                'order' => 6,
                'is_active' => true,
                'permission_name' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'name' => 'Menu Management',
                'route' => 'menus.index',
                'parent_id' => null,
                'icon' => 'fas fa-list',
                'color' => null,
                'order' => 9,
                'is_active' => true,
                'permission_name' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'name' => 'Management Roles',
                'route' => 'roles.index',
                'parent_id' => null,
                'icon' => 'fas fa-key',
                'color' => null,
                'order' => 7,
                'is_active' => true,
                'permission_name' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'name' => 'Management Permission',
                'route' => 'permissions.index',
                'parent_id' => null,
                'icon' => 'fas fa-lock',
                'color' => null,
                'order' => 8,
                'is_active' => true,
                'permission_name' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'name' => 'Dealer',
                'route' => null,
                'parent_id' => null,
                'icon' => 'fas fa-store',
                'color' => null,
                'order' => 2,
                'is_active' => true,
                'permission_name' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 31,
                'name' => 'Order',
                'route' => null,
                'parent_id' => null,
                'icon' => 'fas fa-receipt',
                'color' => null,
                'order' => 3,
                'is_active' => true,
                'permission_name' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 33,
                'name' => 'Sales',
                'route' => 'sales.index',
                'parent_id' => null,
                'icon' => 'fas fa-chart-line',
                'color' => null,
                'order' => 4,
                'is_active' => true,
                'permission_name' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Child menus
            [
                'id' => 3,
                'name' => 'List Products',
                'route' => 'product.index',
                'parent_id' => 2,
                'icon' => null,
                'color' => null,
                'order' => 1,
                'is_active' => true,
                'permission_name' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'name' => 'Import',
                'route' => 'dealer-product.index',
                'parent_id' => 2,
                'icon' => null,
                'color' => null,
                'order' => 2,
                'is_active' => true,
                'permission_name' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'name' => 'Master',
                'route' => 'master-product.index',
                'parent_id' => 2,
                'icon' => null,
                'color' => null,
                'order' => 3,
                'is_active' => true,
                'permission_name' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'name' => 'Distance Sorting Dealer',
                'route' => 'distance-dealer.index',
                'parent_id' => 11,
                'icon' => null,
                'color' => null,
                'order' => 1,
                'is_active' => true,
                'permission_name' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'name' => 'List Dealer',
                'route' => 'dealer.index',
                'parent_id' => 11,
                'icon' => null,
                'color' => null,
                'order' => 2,
                'is_active' => true,
                'permission_name' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'name' => 'List Order',
                'route' => 'order.index',
                'parent_id' => 31,
                'icon' => null,
                'color' => null,
                'order' => 1,
                'is_active' => true,
                'permission_name' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 34,
                'name' => 'Awaiting Order',
                'route' => 'request-order.index',
                'parent_id' => 31,
                'icon' => null,
                'color' => null,
                'order' => 2,
                'is_active' => true,
                'permission_name' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 35,
                'name' => 'Target',
                'route' => 'target.index',
                'parent_id' => null,
                'icon' => 'fas fa-bullseye',
                'color' => null,
                'order' => 5,
                'is_active' => true,
                'permission_name' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 36,
                'name' => 'ROD',
                'route' => 'rod.index',
                'parent_id' => null,
                'icon' => 'fas fa-coins',
                'color' => null,
                'order' => 6,
                'is_active' => true,
                'permission_name' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
