<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('menus')->insert([
            [
                'name' => 'Dashboard',
                'route' => 'dashboard.index',
                'parent_id' => null,
                'icon' => 'fas fa-chart-pie',
                'color' => null,
                'order' => 1,
                'is_active' => 't',
                'permission_name' => null,
                'created_at' => Carbon::parse('2024-12-04 15:28:55'),
                'updated_at' => Carbon::parse('2024-12-04 15:28:55'),
            ],
            [
                'name' => 'Products',
                'route' => null,
                'parent_id' => 2,
                'icon' => 'fas fa-box',
                'color' => null,
                'order' => 2,
                'is_active' => 't',
                'permission_name' => null,
                'created_at' => Carbon::parse('2024-12-04 15:28:55'),
                'updated_at' => Carbon::parse('2024-12-09 10:49:22'),
            ],
            [
                'name' => 'List Products',
                'route' => 'product.index',
                'parent_id' => 2,
                'icon' => null,
                'color' => null,
                'order' => 1,
                'is_active' => 't',
                'permission_name' => null,
                'created_at' => Carbon::parse('2024-12-04 15:28:55'),
                'updated_at' => Carbon::parse('2024-12-04 15:28:55'),
            ],
            [
                'name' => 'Dealer Products',
                'route' => 'dealer-product.index',
                'parent_id' => 2,
                'icon' => null,
                'color' => null,
                'order' => 2,
                'is_active' => 't',
                'permission_name' => null,
                'created_at' => Carbon::parse('2024-12-04 15:28:55'),
                'updated_at' => Carbon::parse('2024-12-04 15:28:55'),
            ],
            [
                'name' => 'List Dealer',
                'route' => 'dealer.index',
                'parent_id' => 11,
                'icon' => null,
                'color' => null,
                'order' => 3,
                'is_active' => 't',
                'permission_name' => null,
                'created_at' => Carbon::parse('2024-12-04 15:28:55'),
                'updated_at' => Carbon::parse('2024-12-13 08:20:44'),
            ],
            [
                'name' => 'Management User',
                'route' => 'users.index',
                'parent_id' => null,
                'icon' => 'fas fa-users',
                'color' => null,
                'order' => 4,
                'is_active' => 't',
                'permission_name' => null,
                'created_at' => Carbon::parse('2024-12-04 15:28:55'),
                'updated_at' => Carbon::parse('2024-12-04 15:28:55'),
            ],
            [
                'name' => 'Menu Management',
                'route' => 'menus.index',
                'parent_id' => null,
                'icon' => 'fas fa-list',
                'color' => null,
                'order' => null,
                'is_active' => 't',
                'permission_name' => null,
                'created_at' => Carbon::parse('2024-12-03 14:14:46'),
                'updated_at' => Carbon::parse('2024-12-03 14:43:19'),
            ],
            [
                'name' => 'Management Roles',
                'route' => 'roles.index',
                'parent_id' => 6,
                'icon' => 'fas fa-key',
                'color' => null,
                'order' => null,
                'is_active' => 't',
                'permission_name' => null,
                'created_at' => Carbon::parse('2024-12-04 15:28:55'),
                'updated_at' => Carbon::parse('2024-12-05 10:40:18'),
            ],
            [
                'name' => 'Management Permission',
                'route' => 'permissions.index',
                'parent_id' => 6,
                'icon' => 'fas fa-lock',
                'color' => null,
                'order' => null,
                'is_active' => 't',
                'permission_name' => null,
                'created_at' => Carbon::parse('2024-12-04 15:28:55'),
                'updated_at' => Carbon::parse('2024-12-05 10:41:15'),
            ],
            [
                'name' => 'Master Product',
                'route' => 'master-product.index',
                'parent_id' => 2,
                'icon' => null,
                'color' => null,
                'order' => null,
                'is_active' => 't',
                'permission_name' => null,
                'created_at' => Carbon::parse('2024-12-09 13:29:12'),
                'updated_at' => Carbon::parse('2024-12-09 13:29:12'),
            ],
            [
                'name' => 'Dealer',
                'route' => null,
                'parent_id' => 3,
                'icon' => 'fas fa-solid fa-store',
                'color' => null,
                'order' => null,
                'is_active' => 't',
                'permission_name' => null,
                'created_at' => Carbon::parse('2024-12-13 08:20:25'),
                'updated_at' => Carbon::parse('2024-12-13 08:21:08'),
            ],
            [
                'name' => 'Distance Sorting Dealer',
                'route' => 'distance-dealer.index',
                'parent_id' => 11,
                'icon' => null,
                'color' => null,
                'order' => null,
                'is_active' => 't',
                'permission_name' => null,
                'created_at' => Carbon::parse('2024-12-13 08:21:56'),
                'updated_at' => Carbon::parse('2024-12-13 08:21:56'),
            ],
            [
                'name' => 'Awaiting Order',
                'route' => 'request-order.index',
                'parent_id' => 15,
                'icon' => null,
                'color' => null,
                'order' => null,
                'is_active' => 't',
                'permission_name' => null,
                'created_at' => Carbon::parse('2024-12-31 11:29:27'),
                'updated_at' => Carbon::parse('2024-12-31 11:29:46'),
            ],
            [
                'name' => 'List Order',
                'route' => 'order.index',
                'parent_id' => 15,
                'icon' => null,
                'color' => null,
                'order' => 3,
                'is_active' => 't',
                'permission_name' => null,
                'created_at' => Carbon::parse('2024-12-13 08:21:56'),
                'updated_at' => Carbon::parse('2024-12-31 11:30:01'),
            ],
            [
                'name' => 'Order',
                'route' => null,
                'parent_id' => 3,
                'icon' => 'fas fa-receipt',
                'color' => null,
                'order' => 3,
                'is_active' => 't',
                'permission_name' => null,
                'created_at' => Carbon::parse('2024-12-31 11:29:36'),
                'updated_at' => Carbon::parse('2024-12-31 11:30:16'),
            ],
        ]);
    }
}
