<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $menus = [
            [
                'id' => 1,
                'name' => 'Dashboard',
                'route' => 'dashboard.index',
                'parent_id' => null,
                'icon' => 'fas fa-chart-pie',
                'color' => null,
                'order' => 1,
                'is_active' => true,
                'permission_name' => null,
                'created_at' => '2024-12-04 15:28:55',
                'updated_at' => '2024-12-04 15:28:55',
            ],
            [
                'id' => 2,
                'name' => 'Products',
                'route' => null,
                'parent_id' => null,
                'icon' => 'fas fa-box',
                'color' => null,
                'order' => 2,
                'is_active' => true,
                'permission_name' => null,
                'created_at' => '2024-12-04 15:28:55',
                'updated_at' => '2024-12-09 10:49:22',
            ],
            [
                'id' => 3,
                'name' => 'List Products',
                'route' => 'product.index',
                'parent_id' => 2,
                'icon' => null,
                'color' => null,
                'order' => 1,
                'is_active' => true,
                'permission_name' => null,
                'created_at' => '2024-12-04 15:28:55',
                'updated_at' => '2024-12-04 15:28:55',
            ],
            [
                'id' => 4,
                'name' => 'Dealer Products',
                'route' => 'dealer-product.index',
                'parent_id' => 2,
                'icon' => null,
                'color' => null,
                'order' => 2,
                'is_active' => true,
                'permission_name' => null,
                'created_at' => '2024-12-04 15:28:55',
                'updated_at' => '2024-12-04 15:28:55',
            ],
            [
                'id' => 5,
                'name' => 'List Dealer',
                'route' => 'dealer.index',
                'parent_id' => 11,
                'icon' => null,
                'color' => null,
                'order' => 3,
                'is_active' => true,
                'permission_name' => null,
                'created_at' => '2024-12-04 15:28:55',
                'updated_at' => '2024-12-13 08:20:44',
            ],
            [
                'id' => 6,
                'name' => 'Management User',
                'route' => 'users.index',
                'parent_id' => null,
                'icon' => 'fas fa-users',
                'color' => null,
                'order' => 4,
                'is_active' => true,
                'permission_name' => null,
                'created_at' => '2024-12-04 15:28:55',
                'updated_at' => '2024-12-04 15:28:55',
            ],
            [
                'id' => 7,
                'name' => 'Menu Management',
                'route' => 'menus.index',
                'parent_id' => null,
                'icon' => 'fas fa-list',
                'color' => null,
                'order' => null,
                'is_active' => true,
                'permission_name' => null,
                'created_at' => '2024-12-03 14:14:46',
                'updated_at' => '2024-12-03 14:43:19',
            ],
            [
                'id' => 8,
                'name' => 'Management Roles',
                'route' => 'roles.index',
                'parent_id' => null,
                'icon' => 'fas fa-key',
                'color' => null,
                'order' => 6,
                'is_active' => true,
                'permission_name' => null,
                'created_at' => '2024-12-04 15:28:55',
                'updated_at' => '2024-12-05 10:40:18',
            ],
            [
                'id' => 9,
                'name' => 'Management Permission',
                'route' => 'permissions.index',
                'parent_id' => null,
                'icon' => 'fas fa-lock',
                'color' => null,
                'order' => 6,
                'is_active' => true,
                'permission_name' => null,
                'created_at' => '2024-12-04 15:28:55',
                'updated_at' => '2024-12-05 10:41:15',
            ],
            [
                'id' => 10,
                'name' => 'Master Product',
                'route' => 'master-product.index',
                'parent_id' => 2,
                'icon' => null,
                'color' => null,
                'order' => null,
                'is_active' => true,
                'permission_name' => null,
                'created_at' => '2024-12-09 13:29:12',
                'updated_at' => '2024-12-09 13:29:12',
            ],
            [
                'id' => 11,
                'name' => 'Dealer',
                'route' => null,
                'parent_id' => null,
                'icon' => 'fas fa-solid fa-store',
                'color' => null,
                'order' => 3,
                'is_active' => true,
                'permission_name' => null,
                'created_at' => '2024-12-13 08:20:25',
                'updated_at' => '2024-12-13 08:21:08',
            ],
            [
                'id' => 12,
                'name' => 'Distance Sorting Dealer',
                'route' => 'distance-dealer.index',
                'parent_id' => 11,
                'icon' => null,
                'color' => null,
                'order' => null,
                'is_active' => true,
                'permission_name' => null,
                'created_at' => '2024-12-13 08:21:56',
                'updated_at' => '2024-12-13 08:21:56',
            ],
        ];

        // Insert menus into the database
        DB::table('menus')->insert($menus);
    }
}
